# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fall_detection.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'fall_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66\x61ll_detection.proto\x12\x0e\x66\x61ll_detection\"@\n\x0b\x46\x61llRequest\x12\x12\n\nframe_data\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\"\x1e\n\x0c\x46\x61llResponse\x12\x0e\n\x06\x66\x61llen\x18\x01 \x01(\x08\x32\x61\n\x14\x46\x61llDetectionService\x12I\n\nDetectFall\x12\x1b.fall_detection.FallRequest\x1a\x1c.fall_detection.FallResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fall_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FALLREQUEST']._serialized_start=40
  _globals['_FALLREQUEST']._serialized_end=104
  _globals['_FALLRESPONSE']._serialized_start=106
  _globals['_FALLRESPONSE']._serialized_end=136
  _globals['_FALLDETECTIONSERVICE']._serialized_start=138
  _globals['_FALLDETECTIONSERVICE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
