# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fall_detection_pb2 as fall__detection__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fall_detection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FallDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectFall = channel.unary_unary(
                '/fall_detection.FallDetectionService/DetectFall',
                request_serializer=fall__detection__pb2.FallRequest.SerializeToString,
                response_deserializer=fall__detection__pb2.FallResponse.FromString,
                _registered_method=True)


class FallDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectFall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FallDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectFall': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFall,
                    request_deserializer=fall__detection__pb2.FallRequest.FromString,
                    response_serializer=fall__detection__pb2.FallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fall_detection.FallDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fall_detection.FallDetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FallDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectFall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fall_detection.FallDetectionService/DetectFall',
            fall__detection__pb2.FallRequest.SerializeToString,
            fall__detection__pb2.FallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
